### PR TITLE
Support local labels

### LINKED ISSUE #6: Support of local labels
Firstly, many thanks for the great project. Secondly, I apologize if GitHub Issues is the wrong place for feature requests.

It would be convenient if suite8080 supported local labels, for instance:

```
@@:          ; local label (1)
   nop
   jmp @B ; jump back to (1)
   nop
   jmp @F ; jump forward to (2)
   nop
@@:         ; local label (2)
  nop
```

The particular syntax is not important. Different assemblers do this differently.

### PR DESCRIPTION
**Pull request by afiskon**
Fixes #6

### CODE REVIEW

**Comment by afiskon** [comment]
Here is a more complicated program I used for manual testing. It produces the same binary output as the previous version which only used global labels. I also tested `@F`.

```
$ md5 ccheck.com ccheck.com.bak
MD5 (ccheck.com) = 8edec51189359ac5fe13cbc69afa65fd
MD5 (ccheck.com.bak) = 8edec51189359ac5fe13cbc69afa65fd
```

```
        org 234                         ; 234 = 0100h - 16 - 3*2

        db 'ISKRA1080', 0D0h, 'CCHECK'
        dw entry
        dw code_end
        dw entry

entry:                                  ; адрес 0100h
        mvi a, 006h
        out 091h                        ; светло-красный для режима 4 цвета

        mvi a, 005h
        out 092h                        ; цвет текста - светло-зеленый

        mvi a, 003h
        out 093h                        ; светло-синий для режима 4 цвета

        xra a                           ; A := 0
        out 090h                        ; цвет фона - белый

        out 0F8h                        ; переходим в режим 4 цветов
        out 0B9h

loop:
        mvi c, 000h
        call fill_main
        call delay
        call fill_secondary
        call delay

        mvi c, 0FFh
        call fill_main
        call delay
        call fill_secondary
        call delay

        jmp loop                        ; программа зациклена

fill_main:                              ; заполнить память D000..FFFF значнием C
        lxi h, 0D000h
@@:
        mov m, c
        inx h
        mvi a, 0FFh
        cmp h                           ; HL достиг FFFF?
        jnz @B
        cmp l
        jnz @B
        mov m, c                        ; запись последнего байта
        ret

fill_secondary:                 ; заполнить память 9000..BFFF значением C
        lxi h, 09000h
@@:
        mov m, c
        inx h
        mvi a, 0BFh
        cmp h                           ; HL достиг BFFF?
        jnz @B
        mvi a, 0FFh
        cmp l
        jnz @B
        mov m, c                        ; запись последнего байта
        ret

delay:                                  ; задержка, не меняет значение C
        mvi a, 0FFh
@@:
        dcr a
        jnz @B
        ret

code_end:
```

**Comment by pamoroso** [comment]
Thanks but, as I said in #6, I'm planning to archive this repo and I have no way of testing the code, so I'd appreciate it if you could fork the repo and apply the changes to the fork.

**Comment by afiskon** [comment]
No problem, I created a fork. Perhaps you could reference it in the README then?

**Comment by pamoroso** [comment]
Apologies, I don't want to sound rude but I prefer not to link to or endorse code I don't know and can't vet.

**Comment by afiskon** [comment]
I understand, no worries 🙏

**Pull request closed without merging**
